name: icpc-reference-tester
on: [pull_request]
jobs:
  check-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: icpc-reference-tester 
    steps:
      - uses: actions/checkout@v2
      - uses: nanasess/setup-chromedriver@master
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - uses: actions-rs/cargo@v1
        with:
          command: run 
          args: --release test/test_folder